include: package:flutter_lints/flutter.yaml
linter:
  rules:
    sort_pub_dependencies: false
    always_put_required_named_parameters_first: true
    avoid_classes_with_only_static_members: false
    always_specify_types: true
    sort_constructors_first: true
    prefer_single_quotes: true
    argument_type_not_assignable: true
    prefer_relative_imports: true
    avoid_relative_lib_imports: true
